# Generated by Django 5.1.5 on 2025-02-11 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0002_ubicacion_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maquinaria.responsable'),
        ),
        migrations.AddField(
            model_name='obra',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maquinaria.ubicacion'),
        ),
        migrations.AddField(
            model_name='responsable',
            name='cargo',
            field=models.CharField(default='Sin especificar', max_length=255),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='ciudad',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
    ]
